# Generated by Django 3.0.3 on 2020-02-22 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200222_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationhistory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 10, 30, 3, 902924), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 10, 30, 3, 903925), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 10, 30, 3, 900905), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 10, 30, 3, 900905), verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='visaappplication',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 10, 30, 3, 902924), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visaappplication',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 10, 30, 3, 902924), verbose_name='date modified'),
        ),
    ]
