# Generated by Django 3.0.3 on 2020-02-22 05:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200222_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 2, 22, 11, 10, 36, 80870), verbose_name='date created')),
                ('date_modified', models.DateTimeField(default=datetime.datetime(2020, 2, 22, 11, 10, 36, 80870), verbose_name='date modified')),
            ],
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 11, 10, 36, 81870), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 11, 10, 36, 81870), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 11, 10, 36, 77867), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 11, 10, 36, 77867), verbose_name='date modified'),
        ),
        migrations.DeleteModel(
            name='VisaAppplication',
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.ApplicationStatus'),
        ),
    ]
