# Generated by Django 3.0.3 on 2020-02-22 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200222_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaapplication',
            name='action_pending_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_pending_on', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='visaapplication',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_by', to='employee.Employee'),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.VisaApplication'),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 15, 5, 16, 601327), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 15, 5, 16, 601327), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 15, 5, 16, 598325), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 15, 5, 16, 598325), verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 15, 5, 16, 600327), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 22, 15, 5, 16, 600327), verbose_name='date modified'),
        ),
        migrations.AlterField(
            model_name='visaapplication',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='employee.Employee'),
        ),
    ]
